version: 0.0
os: windows
files:
  - source: C:\Projects\webapps\publish
    destination: C:\backup\
    file_exists_behavior: OVERWRITE
hooks:
   BeforeInstall:
     - location: stop.bat       
       runas: administrator
   ApplicationStart:
     - location: start.bat       
       runas: administrator
